### ISSUE TITLE
GitHub project cards should have clickable links to author pages

### ISSUE THREAD

**Issue by samtstern** [google/devlibrary#251]
GitHub repositories right now always show the name / photo of the GitHub owner. We _should_ show the DevLibrary author when we have that information and allow clicking through from the card to their profile.

This will require inlining some author information (at least name) into the `RepoData` objects in the database so that this can be done efficiently. Right now we only have `authorIds: []` which is enough to link but not enough to display.

Blog cards already have this feature.

**Comment by garimame** [comment]
Done.
