### ISSUE TITLE
Request to add a repo to dev library which was not having LICENSE before, but it does now!

### ISSUE THREAD

**Issue by jmrchelani** [google/devlibrary#286]
Dear Sir @samtstern 

Link to the main issue: https://github.com/jmrchelani/flutter_portfolio/issues/2

LICENSE (MIT) has been added, would like this repo to be added, Thanks.

**Comment by samtstern** [comment]
@jmrchelani thank you! I actually hadn't deleted your repo yet, so you beat me to it. Your repo will remain on DevLibrary:
https://github.com/google/devlibrary/blob/main/config/flutter/repos/jmrchelani-flutter_portfolio.json

Within 24 hours the repo will be fully visible on the site.

**Comment by jmrchelani** [comment]
Aha, thanks buddy.
