### ISSUE TITLE
LICENSE added to Angular Dockerize

### ISSUE THREAD

**Issue by alkaj** [google/devlibrary#291]
A [license file](https://github.com/alkaj/spa-dockerize/blob/master/LICENSE) was added to the [Angular Dockerize](https://github.com/alkaj/spa-dockerize) so it can be added back to the [dev library](https://devlibrary.withgoogle.com/products/angular)

**Comment by samtstern** [comment]
Added in https://github.com/google/devlibrary/pull/292, your project will appear on the site in abot 24 hours
