### ISSUE TITLE
Some deleted repos are still in the search index

### ISSUE THREAD

**Issue by samtstern** [google/devlibrary#301]
Searching for ridedott shows this result, which does not exist:
<img width="412" alt="Screen Shot 2022-01-06 at 1 17 19 PM" src="https://user-images.githubusercontent.com/8466666/148453443-521b2e49-3946-4594-ab28-1cfca11f4a2d.png">

The repo was renamed here:
https://github.com/google/devlibrary/commit/4535f56a3bb155849b90e2d3a125793449db8e06

This causes logs like this when they are accessed:
<img width="716" alt="Screen Shot 2022-01-06 at 1 18 25 PM" src="https://user-images.githubusercontent.com/8466666/148453533-f7a08498-aea6-4904-aee6-ff658b58f341.png">

**Comment by garimame** [comment]
Search behavior changed and this is no longer an issue.
