### ISSUE TITLE
Adding issue forms to the repo

### ISSUE THREAD

**Issue by MonarchGitHub** [google/devlibrary#441]
I want to add a few issue forms so that it will be convenient for new contributors to open issues. I plan to create  **Bug Report**, and **Feature Request** forms. 

**_The Bug Report issue form will have the following fields_**

- **Description of the bug**
- **How to Reproduce**
- **Expected behavior**

**_The Feature Request issue form will have the following fields_**

- **Is your feature request related to a problem? Please describe.**
- **Describe the solution you'd like**
- **Describe alternatives you've considered**

**Comment by 5wathi** [comment]
Hello @MonarchGitHub , your suggestion is excellent. We are currently in the process of revising our bug tracking and feature request system, and will certainly take your suggestion into consideration. Thank you for sharing it with us!
