### ISSUE TITLE
Missing from devlibrary

### ISSUE THREAD

**Issue by Kaaveh** [google/devlibrary#640]
Hey there,
I got approval emails for submitting my articles and the GitHub repo on 7th March, but I'm not added to the dev-library yet.

**Comment by Kaaveh** [comment]
Here's my submission:

1. https://github.com/Kaaveh/ComposeNews

2. https://proandroiddev.com/an-introduction-about-preview-in-jetpack-compose-b72a96daac35
3. https://proandroiddev.com/all-about-navigation-in-the-jetpack-compose-based-production-code-base-902706b8466d

**Comment by 5wathi** [comment]
@Kaaveh, I think March 7th content is yet to be updated on the website. I'll look into it and get back to you! 
Thanks for reaching out. 

Cc: @gkindavishal

**Comment by 5wathi** [comment]
Adding @shadowshot-x too! If you can take a look at this, and unblock the issues, that'd be great! Thanks Ujjwal

**Comment by Kaaveh** [comment]
Thanks a lot! Now I'm on dev library:

https://devlibrary.withgoogle.com/authors/kaaveh

But, the last issue is my bio 😅 It says: "Android Engineer at GityMarket" according to my Medium account. Some days ago, I changed my company. Please change it to: "Android Engineer at TABDEAL Cryptocurrency Exchange".

Thanks for your support!
@5wathi @shadowshot-x

**Comment by Kaaveh** [comment]
Thank you guys! 🙌🏻

@5wathi @shadowshot-x
