### ISSUE TITLE
Add nightly build/redeploy

### ISSUE THREAD

**Issue by samtstern** [google/devlibrary#65]
We should continuously deploy from source every 24-48h

**Comment by dewanshrawat15** [comment]
@samtstern we can do this by scheduling a GitHub action to run in equal intervals of time, according to [this](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule) or using a Travis job, according to [this](https://docs.travis-ci.com/user/cron-jobs/). A rough plan of action for its implementation and requirements would be:

1. Getting a Firebase token and adding it to the repository secrets (settings -> secrets)
2. Setting up a Travis CI/Github Actions workflow, for building the repository, and deploying it using the tokens
3. Running clean up jobs

**Comment by samtstern** [comment]
We actually use Cloud Build for this project for deployment security
reasons so I can set this up on there, just haven’t gotten around to it
yet.

Appreciate the thoughts though!

**Comment by samtstern** [comment]
Closing this as we decided to do this in our dev environment on every commit, going to keep prod as manually deployed for now.
