### ISSUE TITLE
"Load more" button works only once

### ISSUE THREAD

**Issue by arkivanov** [google/devlibrary#67]
Not sure if it is a bug or a feature, but here it is.

STR:
1. Open the web site: https://devlibrary.withgoogle.com/products/android
2. Click "LOAD MORE" button
3. Scroll to the end

AR: "LOAD MORE" button is not displayed
ER: "LOAD MORE" button is displayed and works

There is definitely more then one page of the data, please see the attached video.

https://user-images.githubusercontent.com/26204457/121337202-30315380-c914-11eb-8bcb-7583ead4ea1f.mp4

**Comment by samtstern** [comment]
Hmmm that's interesting I don't see the same:

https://user-images.githubusercontent.com/8466666/121339578-a02be380-c8ec-11eb-9a0e-18d1a361d29b.mp4

Maybe there's a network or caching error on your side?

**Comment by arkivanov** [comment]
I just tried incognito mode in the Chrome browser. Also specially installed Firefox and tried. Nothing worked, able to click on the button only once. I'm using Ubuntu 20.04.

**Comment by arkivanov** [comment]
However it works in the Android Chrome browser (Android 11). I also noticed different "Blog posts" section content. On desktop (both browsers) the section is empty, but on mobile it has some content.

**Comment by samtstern** [comment]
@arkivanov I think this is probably related to yesterday's Fastly outage. We cache a lot of these responses and the shared cache time is 12h.  Let's check again tomorrow to see if this is resolved.

**Comment by samtstern** [comment]
@arkivanov closing this old issue as I still can't reproduce it so I assume it was a one-time glitch. Thank you for reporting it though!
